#!/usr/bin/with-contenv bash

if ! command -v inotifywait; then
    echo "**** Adding inotify-tools and its deps to package install lists ****"
    echo "inotify-tools" >> /mod-repo-packages-to-install.list
else
    echo "**** inotify-tools already installed, skipping ****"
fi
